const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
const FETCH_ORDERS_FULFILLED = 'FETCH_ORDERS_FULFILLED';
const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';
const SELECT_ORDER = 'SELECT_ORDER';
const FETCH_PRODUCTSORDER_REQUEST = 'FETCH_PRODUCTSORDER_REQUEST';
const FETCH_PRODUCTSORDER_FULLFILLED = 'FETCH_PRODUCTSORDER_FULFILLED';
const FETCH_PRODUCTSORDER_REJECTED = 'FETCH_PRODUCTSORDER_REJECTED';

export default {
  FETCH_ORDERS_REQUEST,
  FETCH_ORDERS_FULFILLED,
  FETCH_ORDERS_REJECTED,
  SELECT_ORDER,
  FETCH_PRODUCTSORDER_REQUEST,
  FETCH_PRODUCTSORDER_FULLFILLED,
  FETCH_PRODUCTSORDER_REJECTED
};
