const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
const FETCH_ORDERS_FULFILLED = 'FETCH_ORDERS_FULFILLED';
const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';

export default {
  FETCH_ORDERS_REQUEST,
  FETCH_ORDERS_FULFILLED,
  FETCH_ORDERS_REJECTED
};
